### ISSUE TITLE
Remove Web IDL (adapt to Web Application Manifest changes)

### ISSUE THREAD

**Issue by foolip** [w3c/web-share-target#103]
In https://github.com/w3c/manifest/commit/32b497c4ca34c9069aa5e545126c252724f370fe, @marcoscaceres removed the use of Web IDL for Web Application Manifest. https://w3c.github.io/web-share-target/ extended that IDL with a `partial dictionary WebAppManifest`, and now needs to be somehow adapted.

**Comment by marcoscaceres** [comment]
Oh yeah, oops... I broke all the things 🎉 ... I subscribe to a "you broke it, you bought it" life philosophy, so let me know if you want me to fix this.

**Comment by foolip** [comment]
@mgiuca @ericwilligers how would you like to handle this?

**Comment by foolip** [comment]
@marcoscaceres are you still volunteering to fix this?

**Comment by marcoscaceres** [comment]
Yes, I can do that. I'll add it to my todo.
