### ISSUE TITLE
Add a non-normative section explaining future plans

### ISSUE THREAD

**Issue by mgiuca** [w3c/web-share-target#55]
We could have a section similar to my [Extensibility of this API](https://wicg.github.io/web-share/#extensibility-of-this-api) section in Web Share. Note that I got some negative feedback on this in WICG/web-share#61.

Raised in w3ctag/design-reviews#221.

**Comment by marcoscaceres** [comment]
heh, I was like... "I wonder who filed w3c/web-share#61?" (guilty!)

But I still hold that we don't need this... future plans are can just be bugs in this repo, with a "feature request" label. The risk of having future plans in the spec is that those plans might change or never happen. It's better, IMO, to have specs that only reflect currently implemented reality.

**Comment by mgiuca** [comment]
I agree.
